### PR TITLE
Use the new session path in the client builder.

### PR DESCRIPTION
**Pull request by pixlwave**
Let's see if this helps CI on https://github.com/matrix-org/matrix-rust-sdk/pull/3514

### CODE REVIEW

**Comment by pixlwave** [comment]
Woohoo, it worked! https://github.com/matrix-org/matrix-rust-sdk/actions/runs/9398430718/job/25883741519

**Comment by poljar** [comment]
Oh, it helped the CI for the PR, but what do we need to do to make it work on the main branch of the SDK? I guess merge this PR?

**Comment by pixlwave** [comment]
I think so yes, re-running the tests now the PR is merged to make sure they pass now.

**Review by kegsay — APPROVED** [review]

**Comment by pixlwave** [comment]
@poljar Its merged now 👍

**Comment by poljar** [comment]
> @poljar Its merged now 👍

Thanks.

**Pull request merged**
